GET http://localhost:8080/resources
Accept: */*
Cache-Control: no-cache

### 必须要有正确的 名为JSESSIONID的Cookie，否则需要登录后才能继续。
POST http://192.168.1.103:8081/auth/oauth/authorize?response_type=code&client_id=R2dpxQ3vPrtfgF72&scope=user_info&state=SjBEGfCx5GD7uJ76dhflHLvsbHlUQ028Q7BeOvkz-D4%3D&redirect_uri=http://192.168.1.103:8082/login/oauth2/code/
Cookie: JSESSIONID=5ADE859445EDEC5FECF7754493C597B4; Path=/auth; HttpOnly


###
http://192.168.1.103:8083/authPage/login?response_type=code&client_id=R2dpxQ3vPrtfgF72&scope=user_info&state=SjBEGfCx5GD7uJ76dhflHLvsbHlUQ028Q7BeOvkz-D4=&redirect_uri=http://192.168.1.103:8082/login/oauth2/code/&isRedirect=true

###
POST http://192.168.1.103:8081/auth/login
Content-Type: application/x-www-form-urlencoded

username=a&password=1

###

POST http://192.168.1.103:8081/auth/oauth/authorize?response_type=code&client_id=R2dpxQ3vPrtfgF72&scope=user_info&state=SjBEGfCx5GD7uJ76dhflHLvsbHlUQ028Q7BeOvkz-D4=&redirect_uri=http://192.168.1.103:8082/login/oauth2/code/&isRedirect=true
# 如果oauth/authorize 不被保护， 则 o server后台错误： org.springframework.security.authentication.InsufficientAuthenticationException: User must be authenticated with Spring Security before authorization can be completed.
# 否则o server后台没有错误； 302 到登录页

# 访问 http://192.168.1.103:8081/auth/oauth/authorize?response_type=code&client_id=R2dpxQ3vPrtfgF72&scope=user_info&st 会什么会被302到登录页？ 而我其实已经方向了它
# 访问 http://192.168.1.103:8081/auth/oauth/authorize?response_type=code 却是返回401 error="invalid_client", error_description="Bad client credentials"
# 这个是因为，client_id参数不能少，而且必须能查到。 查不到则o server后台错误（其实是INFO级别）： AuthorizationEndpoint        : Handling ClientRegistrationException error: No client with requested id: 123
###
GET http://192.168.1.103:8081/auth/oauth/authorize?response_type=code&client_id=R2dpxQ3vPrtfgF72
# o server后台没有错误； 302 到登录页

###
#?client_id=7dd33c1a56813db7f797&redirect_uri=http://localhost:8999/v1/user/login&client_secret=de51eecf4d0b887ee9ddbe13019d664d09a6150f&code=69df6eb702a1422ff596
POST http://192.168.1.103:8081/auth/oauth/token?client_id=R2dpxQ3vPrtfgF72&client_secret=fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9&grant_type=authorization_code&redirect_uri=http://192.168.1.103:8082/login/oauth2/code/&code=sBvd5I&state=SjBEGfCx5GD7uJ76dhflHLvsbHlUQ028Q7BeOvkz-D4%3D


### &scope=user_info

GET http://192.168.1.103:8081/auth/user/me
Accept: application/json
Authorization: Bearer 2c94c323-e038-427f-9263-415b8909abcc
User-Agent: Java/1.8.0_231
Host: 192.168.1.103:8081
Connection: keep-alive
Cookie: JSESSIONID=52E2B06BCD0376DF899F046E1C82CDFA; JSESSIONID=6DFC6E266D7BAAF6302D358DC9E748CF

###


